export const FETCH_ALL_PRODUCTS_STARTED = 'FETCH_ALL_PRODUCTS_STARTED';
export const FETCH_ALL_PRODUCTS_LOADED = 'FETCH_ALL_PRODUCTS_LOADED';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';

export const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';

export const FETCH_PRODUCT_DETAILS_START = 'FETCH_PRODUCT_DETAILS_START';
export const FETCH_PRODUCT_DETAILS_LOADED = 'FETCH_PRODUCT_DETAILS_LOADED';
export const FETCH_PRODUCT_DETAILS_ERROR = 'FETCH_PRODUCT_DETAILS_ERROR';
