export const FETCH_ALL_PRODUCTS_STARTED = 'FETCH_ALL_PRODUCTS_STARTED';
export const FETCH_ALL_PRODUCTS_LOADED = 'FETCH_ALL_PRODUCTS_LOADED';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';
